### ISSUE TITLE
Make multi-contract compatible

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/forge-template#42]
Right now, this template works great if you just want to deploy 1 contract. However, a lot of people would be interested in deploying many contracts. For example:

Per the README.md
> Contracts can be deployed via the make deploy command. Addresses are automatically written in a name-address json file stored under out/addresses.json.

If I have two files that I deploy, they will be overwritten on subsequent deployments. Additionally, the deploy scripts really only work with one contract.

Love the project, hopefully these are good bits of feedback.

**Comment by gakonst** [comment]
closing as deployment is coming soon^TM with `forge deploy`
