### ISSUE TITLE
Packages not found

### ISSUE THREAD

**Issue by Divide-By-0** [foundry-rs/forge-template#45]
I'm running a fully shell script that calls the uniswap address with some custom transaction data. It crashes, so I put a `seth call --debug $unicontract $unicalldata`. Now, it says 'hevm: @openzeppelin/contracts/drafts/IERC20Permit.sol: openBinaryFile: does not exist (No such file or directory)'. Any idea why this happens? I grabbed a generic IERC20Permit.sol off github and stuck it in that directory under node_modules, but no beans.

**Comment by gakonst** [comment]
this is unrelated to the template, so closing
